import { BorrowedAsset, columns } from "./borrowedColumns";
import { BorrowedDataTable } from "./borrowedTable";
import { Dialog } from "./ui/dialog";

export default function Borrowed() {
  const data: BorrowedAsset[] = [
    {
      borrow_transaction_id: "1",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 1,
      employee_name: "Jewel Lei 1",
      asset_id: 1,
      asset_name: "Borrowed Asset 1",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "2",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 2,
      employee_name: "Jewel Lei 2",
      asset_id: 2,
      asset_name: "Borrowed Asset 2",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "3",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 3,
      employee_name: "Jewel Lei 3",
      asset_id: 3,
      asset_name: "Borrowed Asset 3",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "4",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 4,
      employee_name: "Jewel Lei 4",
      asset_id: 4,
      asset_name: "Borrowed Asset 4",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "5",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 5,
      employee_name: "Jewel Lei 5",
      asset_id: 5,
      asset_name: "Borrowed Asset 5",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "6",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 6,
      employee_name: "Jewel Lei 6",
      asset_id: 6,
      asset_name: "Borrowed Asset 6",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "7",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 7,
      employee_name: "Jewel Lei 7",
      asset_id: 7,
      asset_name: "Borrowed Asset 7",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "8",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 8,
      employee_name: "Jewel Lei 8",
      asset_id: 8,
      asset_name: "Borrowed Asset 8",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "9",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 9,
      employee_name: "Jewel Lei 9",
      asset_id: 9,
      asset_name: "Borrowed Asset 9",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "10",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 10,
      employee_name: "Jewel Lei 10",
      asset_id: 10,
      asset_name: "Borrowed Asset 10",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
    {
      borrow_transaction_id: "11",
      company_id: 1,
      company_name: "UNAI",
      department_id: 1,
      department_name: "ISTI",
      unit_id: 1,
      unit_name: "None",
      user_id: 11,
      employee_name: "Jewel Lei 11",
      asset_id: 11,
      asset_name: "Borrowed Asset 11",
      date_borrowed: "02/24/2025",
      due_date: "N/A",
      return_date: "N/A",
      duration: "100 days",
      asset_condition_id: "",
      asset_condition_name: "Good",
      remarks: "None",
    },
  ];

  return (
    <>
      <Dialog>
        <div className="ml-[calc(7rem+10px)] mt-[calc(1.5rem+10px)] w-screen mr-10 mb-10 min-h-[calc(100vh-10rem)] max-h-[calc(100vh-10rem)] bg-white rounded-xl">
          <p className="font-medium text-lg mt-5 px-10">Borrowed Assets</p>
          <div className="flex-1 min-h-0">
            <BorrowedDataTable columns={columns} data={data} />
          </div>
        </div>
      </Dialog>
    </>
  );
}
