import { ExternalAsset, columns } from "./externalAssetsColumns";
import { ExternalDataTable } from "./externalTable";

function External() {
  const data: ExternalAsset[] = [
    {
      asset_id: "728ed52a",
      asset_name: "External Asset 1",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52a",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52b",
      asset_name: "External Asset 2",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52b",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52c",
      asset_name: "External Asset 3",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52c",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52d",
      asset_name: "External Asset 4",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52d",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52e",
      asset_name: "External Asset 5",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52e",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52f",
      asset_name: "External Asset 6",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52f",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52g",
      asset_name: "External Asset 7",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52g",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52h",
      asset_name: "External Asset 8",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52h",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52i",
      asset_name: "External Asset 9",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52i",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52j",
      asset_name: "External Asset 10",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52j",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
    {
      asset_id: "728ed52k",
      asset_name: "External Asset 11",
      category_id: 1,
      category_name: "External",
      sub_category_id: 1,
      sub_category_name: "Gantry Routers",
      type_id: 1,
      type_name: "None",
      asset_condition_id: 1,
      asset_condition_name: "Good",
      location: "ISTI Dept",
      availability_status: "Available",
      serial_number: "728ed52k",
      specifications: "eme",
      asset_amount: 7000,
      warranty_duration: 2,
      warranty_due_date: "02/24/2027",
      purchase_date: "02/24/2025",
      aging: 0,
      notes: "eme",
    },
  ];
  return (
    <>
      <div className="bg-white rounded-xl min-h-[calc(100vh-13.10rem)] max-h-[calc(100vh-13.10rem)] flex flex-col">
        <p className="font-medium text-lg px-10 pt-4">External Assets</p>
        <div className="flex-1 min-h-0">
          <ExternalDataTable columns={columns} data={data} />
        </div>
      </div>
    </>
  );
}

export default External;
